{"name": "Creating order with wrong ingredient", "status": "passed", "start": 1726995263062, "stop": 1726995263404, "uuid": "b36852bf-4ab5-4d23-bd3e-3a7403bb0830", "historyId": "7cede9047e6079cd16a91c6112cca11e", "testCaseId": "7cede9047e6079cd16a91c6112cca11e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_wrong_ingredient_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "anastasaslaptop.tailb0c67.ts.net"}, {"name": "thread", "value": "62240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}