{"name": "Creating order with wrong ingredient", "status": "passed", "start": 1726938186169, "stop": 1726938186520, "uuid": "397804cb-40f8-422f-8f2a-adc9d2cdea08", "historyId": "7cede9047e6079cd16a91c6112cca11e", "testCaseId": "7cede9047e6079cd16a91c6112cca11e", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_wrong_ingredient_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "anastasaslaptop.tailb0c67.ts.net"}, {"name": "thread", "value": "39849-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}